### ISSUE TITLE
How do I remove the description field?

### ISSUE THREAD

**Issue by kiarafrobles** [minamo173/hexo-tag-link-preview#2]

**Comment by minamo173** [comment]
Thanks for asking.
There is no way to remove description field now 🙇 

But, I think better there's it. 👍 

I'll implement a option you remove description.
Please wait.

**Comment by jusx** [comment]
Alternatively you could use CSS to hide the element:

```css
.link-preview .og-description {
  display: none;
}
```
